import type { ViewSettings } from "../viewSettings";

const px = (value: number): string => `${value}px`;

/** CSS custom properties consumed by style/visual.less (same names as v2.7.1.0). */
export function cssVariables(s: ViewSettings): ReadonlyArray<readonly [string, string]> {
    return [
        ["--font-family", `"${s.fontFamily}", DIN, "DIN Next", "Segoe UI", Arial, sans-serif`],
        ["--item-font-size", px(s.itemFontSize)],
        ["--domain-font-size", px(s.domainFontSize)],
        ["--group-font-size", px(s.groupFontSize)],
        ["--counter-font-size", px(s.counterFontSize)],
        ["--section-title-font-size", px(s.sectionTitleFontSize)],
        ["--line-height", String(s.lineHeight / 100)],
        ["--letter-spacing", px(s.letterSpacing)],
        ["--item-weight", s.itemBold ? "700" : "400"],
        ["--group-weight", s.groupBold ? "700" : "500"],
        ["--area-weight", s.areaBold ? "700" : "400"],
        ["--font-style", s.italic ? "italic" : "normal"],
        ["--row-min-height", px(s.rowMinHeight)],
        ["--vertical-padding", px(s.verticalPadding)],
        ["--horizontal-padding", px(s.horizontalPadding)],
        ["--outer-padding", px(s.outerPadding)],
        ["--row-gap", px(s.rowGap)],
        ["--group-gap", px(s.groupGap)],
        ["--control-gap", px(s.controlGap)],
        ["--domain-indent", px(s.domainIndent)],
        ["--item-indent", px(s.itemIndent)],
        ["--badge-size", px(s.badgeSize)],
        ["--button-size", px(s.buttonSize)],
        ["--icon-font-size", px(s.iconFontSize)],
        ["--corner-radius", px(s.cornerRadius)],
        ["--selected-panel-padding", px(s.selectedPanelPadding)],
        ["--badge-border-width", px(s.badgeBorderWidth)],
        ["--visual-background", s.backgroundColor],
        ["--text-color", s.textColor],
        ["--secondary-text-color", s.secondaryTextColor],
        ["--accent-color", s.accentColor],
        ["--selected-text-color", s.selectedTextColor],
        ["--selected-row-background", s.selectedRowBackground],
        ["--hover-background", s.hoverBackground],
        ["--area-background", s.areaBackground],
        ["--group-background", s.groupBackground],
        ["--panel-background", s.panelBackground],
        ["--panel-border-color", s.panelBorderColor],
        ["--badge-border-color", s.badgeBorderColor],
        ["--button-hover-background", s.buttonHoverBackground],
        ["--scrollbar-width", px(s.scrollbarWidth)],
        ["--scrollbar-thumb", s.scrollbarThumb],
        ["--scrollbar-track", s.scrollbarTrack],
        ["--toolbar-button-size", px(s.toolbarButtonSize)],
        ["--toolbar-icon-size", px(s.toolbarIconSize)],
        ["--toolbar-gap", px(s.toolbarGap)],
        ["--toolbar-background", s.toolbarBackground],
        ["--toolbar-button-color", s.toolbarButtonColor],
    ];
}
